### ISSUE TITLE
Jedi completion bug

### ISSUE THREAD

**Issue by anntzer** [ipython/ipython#9460]
I know master's not stable, but I guess this may be of interest for the developers...

As of today:

```
$ echo 'def foo(a, b=1, *, c=2): pass' > foo.py && ipython
Python 3.5.1 (default, Mar  3 2016, 09:29:07) 
Type "copyright", "credits" or "license" for more information.

IPython 5.0.0.dev -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.
Using matplotlib backend: Qt5Agg

In [1]: from foo import foo

In [2]: foo("f<tab>Exception in thread Thread-27: # <--- <tab> here
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.5/site-packages/prompt_toolkit/interface.py", line 759, in run
    completions = list(buffer.completer.get_completions(document, complete_event))
  File "/usr/lib/python3.5/site-packages/IPython/terminal/ptshell.py", line 49, in get_completis
    cursor_pos=document.cursor_position_col
  File "/usr/lib/python3.5/site-packages/IPython/core/completer.py", line 1268, in complete
    self.matches.extend(self.python_jedi_matches(text, line_buffer, cursor_pos))
  File "/usr/lib/python3.5/site-packages/IPython/core/completer.py", line 816, in python_jedi_ms
    completions = interpreter.completions()
  File "/usr/lib/python3.5/site-packages/jedi/api/__init__.py", line 197, in completions
    for p in call_sig.params:
  File "/usr/lib/python3.5/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/usr/lib/python3.5/site-packages/jedi/api/classes.py", line 352, in params
    return [_Param(self._evaluator, p.name) for p in params]
  File "/usr/lib/python3.5/site-packages/jedi/api/classes.py", line 352, in <listcomp>
    return [_Param(self._evaluator, p.name) for p in params]
  File "/usr/lib/python3.5/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/usr/lib/python3.5/site-packages/jedi/evaluate/cache.py", line 58, in __call__
    return super(CachedMetaClass, self).__call__(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/jedi/api/classes.py", line 508, in __init__
    super(Definition, self).__init__(evaluator, definition)
  File "/usr/lib/python3.5/site-packages/jedi/api/classes.py", line 64, in __init__
    self._definition = evaluator.wrap(self._name.get_definition())
AttributeError: 'Operator' object has no attribute 'get_definition'
```

**Comment by Carreau** [comment]
What the content of your `foo.py` ? But in general I think we are going to revert jedi integration for 5.0 and rework on it in 6.0.

**Comment by anntzer** [comment]
It's in the first line:
```
$ echo 'def foo(a, b=1, *, c=2): pass' > foo.py && ipython
```

**Comment by Carreau** [comment]
Closed by #10182
