### ISSUE TITLE
AttributeError: 'PtkHistoryAdapter' object has no attribute '_loaded'

### ISSUE THREAD

**Issue by duttasandipan** [ipython/ipython#13645]
Traceback (most recent call last):
  File "/usr/local/bin/ipython", line 8, in <module>
    sys.exit(start_ipython())
  File "/usr/local/lib/python3.8/dist-packages/IPython/__init__.py", line 123, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/traitlets/config/application.py", line 845, in launch_instance
    app.initialize(argv)
  File "/usr/local/lib/python3.8/dist-packages/traitlets/config/application.py", line 88, in inner
    return method(app, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/IPython/terminal/ipapp.py", line 279, in initialize
    self.init_shell()
  File "/usr/local/lib/python3.8/dist-packages/IPython/terminal/ipapp.py", line 293, in init_shell
    self.shell = self.interactive_shell_class.instance(parent=self,
  File "/usr/local/lib/python3.8/dist-packages/traitlets/config/configurable.py", line 540, in instance
    inst = cls(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/IPython/terminal/interactiveshell.py", line 648, in __init__
    self.init_prompt_toolkit_cli()
  File "/usr/local/lib/python3.8/dist-packages/IPython/terminal/interactiveshell.py", line 437, in init_prompt_toolkit_cli
    history = PtkHistoryAdapter(self)
  File "/usr/local/lib/python3.8/dist-packages/IPython/terminal/interactiveshell.py", line 143, in __init__
    self._refresh()
  File "/usr/local/lib/python3.8/dist-packages/IPython/terminal/interactiveshell.py", line 151, in _refresh
    if not self._loaded:
AttributeError: 'PtkHistoryAdapter' object has no attribute '_loaded'

If you suspect this is an IPython 8.2.0 bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

**Comment by Zane-** [comment]
Getting this too when running python3 -m IPython
```
❯ python3 --version
Python 3.8.10
```

**Comment by eight-times** [comment]
Same problem here 

```
> ipython --version
8.2.0

> python3 --version
Python 3.8.10
```

**Comment by NathanDunfield** [comment]
I believe this is a conflict between `IPython 8.2.0` and `prompt_toolkit 2.0.10`.  If I upgrade to `prompt_toolkit `prompt_toolkit 3.0.29` the error goes away and IPython works normally.   It looks like the offending line was introduced in https://github.com/ipython/ipython/pull/13592 .

**Comment by NathanDunfield** [comment]
In more depth, the class `prompt_toolkit.history.History` has an attribute `_loading` in version 2 and `_loaded` in version 3 that play similar, but possibly not quite equivalent roles.  IPython 8.2 sets and tests the latter but not the former.

**Comment by duttasandipan** [comment]
@NathanDunfield Thanks a lot :) It worked. I am able to use ipython now.

**Comment by NathanDunfield** [comment]
@duttasandipan  Glad to hear it worked for you, but I think you should reopen this issue.  IPython is supposed to work with both versions of `prompt_toolkit`, so this does need to get fixed.

**Comment by Korolev-Oleg** [comment]
> I believe this is a conflict between `IPython 8.2.0` and `prompt_toolkit 2.0.10`. If I upgrade to `prompt_toolkit 3.0.29` the error goes away and IPython works normally. It looks like the offending line was introduced in #13592.

I have `prompt_toolkit 3.0.29` `Python 3.8.10`  `IPython 8.2.0`  and same problem - `AttributeError: 'PtkHistoryAdapter' object has no attribute '_loaded'` on `Ubuntu 20.04`

**Comment by ParaPimo** [comment]
`pip3 install --upgrade prompt_toolkit` saved the day for me.

this crashed:
```
prompt_toolkit 2.0.10
python3 3.8.10
ipython 8.3.0
```

this is now ok:
```
prompt_toolkit 3.0.29
python3 3.8.10
ipython 8.3.0
```

**Comment by saviour123** [comment]
> `pip3 install --upgrade prompt_toolkit` saved the day for me.
> 
> this crashed:
> 
> ```
> prompt_toolkit 2.0.10
> python3 3.8.10
> ipython 8.3.0
> ```
> 
> this is now ok:
> 
> ```
> prompt_toolkit 3.0.29
> python3 3.8.10
> ipython 8.3.0
> ```

This worked for me
