### ISSUE TITLE
getting "AttributeError: 'For' object has no attribute 'value'" with ipython=7.6.0

### ISSUE THREAD

**Issue by fehiepsi** [ipython/ipython#11809]
Hi ipython dev, I am facing an issue with the latest version of ipython (7.6.0), python 3.6. The following repro script shows the issue in a Jupyter notebook cell:
```
%%time
x = 1
for i in range(3):
    x += 1
```
It used to work fine with version 7.5.0.

**Comment by Carreau** [comment]
Do you mind trying #11812 ? If it fixes it; I'll try to make a release before Friday.

**Comment by fehiepsi** [comment]
Thanks @Carreau, #11812 works great in my tests!

**Comment by Carreau** [comment]
Ok, great !

I'll wait for CI t pass, travis seem to have some backlog; and release soon.

**Comment by Carreau** [comment]
7.6.1 should be released now with the fix.

**Comment by fehiepsi** [comment]
Thanks @Carreau !
