### ISSUE TITLE
Trying to use ipdb to debug setup.py - triggers TypeError about inputhook

### ISSUE THREAD

**Issue by sr-murthy** [ipython/ipython#11994]
Hi

I'm trying to use ipdb to debug a `setup.py` file (in another package), but I am getting this strange error below. I am working in a Python 3.7 (3.7.4) virtual env. - this is strange, because I never got this error when working with 3.6 (3.6.8).

    Traceback (most recent call last):
      File "/Users/srm/Documents/dev/devenv/lib/python3.7/site-packages/ipdb/__main__.py", line 47, in _init_pdb
        p = debugger_cls(context=context)
      File "/Users/srm/Documents/dev/devenv/lib/python3.7/site-packages/IPython/terminal/debugger.py", line 27, in __init__
        self.pt_init()
      File "/Users/srm/Documents/dev/devenv/lib/python3.7/site-packages/IPython/terminal/debugger.py", line 63, in pt_init
        color_depth=self.shell.color_depth,
    TypeError: __init__() got an unexpected keyword argument 'inputhook'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "setup.py", line 87, in <module>
        import ipdb; ipdb.set_trace()
      File "/Users/srm/Documents/dev/devenv/lib/python3.7/site-packages/ipdb/__main__.py", line 66, in set_trace
        p = _init_pdb(context).set_trace(frame)
      File "/Users/srm/Documents/dev/devenv/lib/python3.7/site-packages/ipdb/__main__.py", line 49, in _init_pdb
        p = debugger_cls()
      File "/Users/srm/Documents/dev/devenv/lib/python3.7/site-packages/IPython/terminal/debugger.py", line 27, in __init__
        self.pt_init()
      File "/Users/srm/Documents/dev/devenv/lib/python3.7/site-packages/IPython/terminal/debugger.py", line 63, in pt_init
        color_depth=self.shell.color_depth,
    TypeError: __init__() got an unexpected keyword argument 'inputhook'

    If you suspect this is an IPython bug, please report it at:
        https://github.com/ipython/ipython/issues
    or send an email to the mailing list at ipython-dev@python.org

    You can print a more detailed traceback right now with "%tb", or use "%debug"
    to interactively debug it.

    Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
        %config Application.verbose_crash=True

**Comment by Carreau** [comment]
duplicate of #11962 will be closed by #11979
