### ISSUE TITLE
IPython crash when use showtraceback with exception_only=True

### ISSUE THREAD

**Issue by MiklosTacs** [ipython/ipython#12831]
Used IPython version: 7.20.0-py38hd4e2768_1

The following exception was raised:
```
Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\IPython\core\ultratb.py", line 1103, in get_records
    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)
  File "C:\Anaconda3\lib\site-packages\IPython\core\ultratb.py", line 248, in wrapped
    return f(*args, **kwargs)
  File "C:\Anaconda3\lib\site-packages\IPython\core\ultratb.py", line 281, in _fixed_getinnerframes
    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))
  File "C:\Anaconda3\lib\inspect.py", line 1503, in getinnerframes
    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)
AttributeError: 'tuple' object has no attribute 'tb_frame'
```

And when this exception is caught in IPython.core.ultratb.VerboseTB.get_records, the return value is None:

    def get_records(self, etb, number_of_lines_of_context, tb_offset):
        try:
            # Try the default getinnerframes and Alex's: Alex's fixes some
            # problems, but it generates empty tracebacks for console errors
            # (5 blanks lines) where none should be returned.
            return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)
        except UnicodeDecodeError:
            # This can occur if a file's encoding magic comment is wrong.
            # I can't see a way to recover without duplicating a bunch of code
            # from the stdlib traceback module. --TK
            error('\nUnicodeDecodeError while processing traceback.\n')
            return None
        **except:
            # FIXME: I've been getting many crash reports from python 2.3
            # users, traceable to inspect.py.  If I can find a small test-case
            # to reproduce this, I should either write a better workaround or
            # file a bug report against inspect (if that's the real problem).
            # So far, I haven't been able to find an isolated example to
            # reproduce the problem.
            inspect_error()
            traceback.print_exc(file=self.ostream)
            info('\nUnfortunately, your original traceback can not be constructed.\n')
            return None**

But the next operation with return value that it is called len() in IPython.core.ultratb.find_recursion, and this causes an exception and IPython crash.

**Comment by MrMino** [comment]
Could you please show us the code needed to reproduce this?

**Comment by MrMino** [comment]
Hi @MiklosTacs. Thank you for reporting this issue - could you please show us the code needed to reproduce this? This will make it easier for other people to debug your problem and, in effect - fix it.

**Comment by alexmojaki** [comment]
This code has been completely overhauled, particularly get_records in https://github.com/ipython/ipython/commit/221eb78a8e09cea6c1634ae71fdc8621a2fe05df#diff-3a77d00d5690f670e9ac680f06b8ffe7ca902c6d325673f32e719d8e55b11ae3, so I doubt this still applies.

**Comment by MrMino** [comment]
Based on the lack of response, and inability to reproduce it, I'm going to assume that this is no longer an issue.

@MiklosTacs If it still affects us, let us know, and give us the code to reproduce it - I'll reopen the issue.

**Comment by MiklosTacs** [comment]
I will open another one ;)

**Comment by MrMino** [comment]
@MiklosTacs please keep this to one issue, do not open duplicates.

**Comment by MrMino** [comment]
> I cannot prove code which helps to reproduce the bug because of my company policy other hand special HW (SWHIL) is also necessary.

Well... unless you can provide any kind of a small toy example of how to trigger it we probably won't be able to help you. No magicians around these parts :).

You still haven't told us whether this is still an issue for you on IPython 7.27.

**Comment by alexmojaki** [comment]
The traceback code is overhauled in master for 8.0, so it could still easily be in 7.27.

**Comment by MrMino** [comment]
@alexmojaki Oh, right, I don't know why but I assumed this has been said, then acted like it's clear :disappointed_relieved::

@MiklosTacs Please try to reproduce it on IPython 7.27.0 and on `master`.

**Comment by MiklosTacs** [comment]
IPython 7.27.0 works properly

**Comment by swan001** [comment]
Hi. I think the issue is still existing. On my side I manage to reproduce the issue with click library. The minimal code snippet is below.

```python
import click

@click.command()
@click.option('--nb_files', type=int, help='number of files to load')
def execute_job(nb_files):
    print('hello world', nb_files)
    return nb_files

if __name__ == '__main__':
    execute_job()
```

Then executed in IPython with the following argugments:
```shell
--nb_files 20
```
I encounter the issue with IPython version 7.22.0 , on Databricks platform using a "Python" job (actions with them are also ongoing).

Should we create a different issue for this one in case this is specific to click? Let me know. Thanks.

**Comment by AlexF1994** [comment]
Same issue here with IPython version 7.27.0 on Databricks, are there any news on that?

**Comment by AlexF1994** [comment]
It seems that click is calling a `system.exit(0)` after your app has finished and ipython mistakes this as an error. We solved the problem by wrapping our application in a try except block:
```Python
try:
    app()
except SystemExit as e:
    if e.code != 0:
        raise
```

**Comment by MrMino** [comment]
Reopening due to reports from @swan001 and @andrijana-lebesgue (#13609)

**Comment by lmgarret** [comment]
I have been running into the same error, and tried to reproduce it with a minimal example. I only managed to get it the same error via a jupyter notebook, here is some info if it can help:

### Setup
python: 3.9.18
Ubuntu 22.04 jammy
```
$ pip list  # kept only the interesting dependencies
Package                   Version      Editable project location
------------------------- ------------ -------------------------
ipykernel                 6.25.2
ipython                   8.18.1
ipywidgets                8.1.1
jupyter_client            8.6.0
jupyter_core              5.5.0
jupyter-events            0.9.0
jupyter-lsp               2.2.1
jupyter_server            2.11.1
jupyter_server_terminals  0.4.4
jupyterlab                4.0.9
jupyterlab_pygments       0.3.0
jupyterlab_server         2.24.0
jupyterlab-widgets        3.0.9
```

### Code
In a notebook:
```python
import traceback
from types import TracebackType
from typing import Optional, Type

from IPython import get_ipython
from IPython.core.interactiveshell import InteractiveShell


class FooExc(Exception):
    pass

def my_handler(
    self: InteractiveShell, etype: Type[BaseException], value: BaseException, tb: TracebackType, tb_offset: Optional[int] = None
):
    self.showtraceback(exc_tuple=(etype, value, tb), filename=None, tb_offset=tb_offset, exception_only=True)
    return traceback.format_tb(tb, tb_offset)

get_ipython().set_custom_exc((FooExc,), my_handler)
raise FooExc("outer exception") from Exception("outer exception")
```
The custom handler does not do much and simply prints the exception's traceback, using `exception_only=True`

### Logs
In short, this raises:
```python

AttributeError: 'tuple' object has no attribute 'tb_frame'


During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
    [... skipping hidden 1 frame]

File venv/lib/python3.9/site-packages/IPython/core/interactiveshell.py:2011, in InteractiveShell.set_custom_exc.<locals>.wrapped(self, etype, value, tb, tb_offset)
   2009     print(self.InteractiveTB.stb2text(stb))
   2010     print("The original exception:")
-> 2011     stb = self.InteractiveTB.structured_traceback(
   2012                             (etype,value,tb), tb_offset=tb_offset
   2013     )
   2014 return stb

TypeError: structured_traceback() missing 1 required positional argument: 'evalue'
```

<details>
  <summary>Click to see complete logs</summary>
  
```python
Custom TB Handler failed, unregistering
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
Exception: outer exception

The above exception was the direct cause of the following exception:

FooExc                                    Traceback (most recent call last)
    [... skipping hidden 1 frame]

Cell In[7], line 1
----> 1 raise FooExc("outer exception") from Exception("outer exception")

FooExc: outer exception

During handling of the above exception, another exception occurred:

AttributeError                            Traceback (most recent call last)
Cell In[5], line 16, in my_handler(self, etype, value, tb, tb_offset)
     12 def my_handler(
     13     self: InteractiveShell, etype: Type[BaseException], value: BaseException, tb: TracebackType, tb_offset: Optional[int] = None
     14 ):  
     15     breakpoint()
---> 16     self.showtraceback(exc_tuple=(etype, value, tb), filename=None, tb_offset=tb_offset, exception_only=True)
     17     return traceback.format_tb(tb, tb_offset)

File venv/lib/python3.9/site-packages/IPython/core/interactiveshell.py:2123, in InteractiveShell.showtraceback(self, exc_tuple, filename, tb_offset, exception_only, running_compiled_code)
   2119     breakpoint()
   2121     stb = ['An exception has occurred, use %tb to see '
   2122            'the full traceback.\n']
-> 2123     stb.extend(self.InteractiveTB.get_exception_only(etype,
   2124                                                      value))
   2125 else:
   2127     def contains_exceptiongroup(val):

File venv/lib/python3.9/site-packages/IPython/core/ultratb.py:710, in ListTB.get_exception_only(self, etype, value)
    702 def get_exception_only(self, etype, value):
    703     """Only print the exception type and message, without a traceback.
    704 
    705     Parameters
   (...)
    708     value : exception value
    709     """
--> 710     return ListTB.structured_traceback(self, etype, value)

File venv/lib/python3.9/site-packages/IPython/core/ultratb.py:568, in ListTB.structured_traceback(self, etype, evalue, etb, tb_offset, context)
    565     chained_exc_ids.add(id(exception[1]))
    566     chained_exceptions_tb_offset = 0
    567     out_list = (
--> 568         self.structured_traceback(
    569             etype,
    570             evalue,
    571             (etb, chained_exc_ids),  # type: ignore
    572             chained_exceptions_tb_offset,
    573             context,
    574         )
    575         + chained_exception_message
    576         + out_list)
    578 return out_list

File venv/lib/python3.9/site-packages/IPython/core/ultratb.py:1435, in AutoFormattedTB.structured_traceback(self, etype, evalue, etb, tb_offset, number_of_lines_of_context)
   1433 else:
   1434     self.tb = etb
-> 1435 return FormattedTB.structured_traceback(
   1436     self, etype, evalue, etb, tb_offset, number_of_lines_of_context
   1437 )

File venv/lib/python3.9/site-packages/IPython/core/ultratb.py:1326, in FormattedTB.structured_traceback(self, etype, value, tb, tb_offset, number_of_lines_of_context)
   1323 mode = self.mode
   1324 if mode in self.verbose_modes:
   1325     # Verbose modes need a full traceback
-> 1326     return VerboseTB.structured_traceback(
   1327         self, etype, value, tb, tb_offset, number_of_lines_of_context
   1328     )
   1329 elif mode == 'Minimal':
   1330     return ListTB.get_exception_only(self, etype, value)

File venv/lib/python3.9/site-packages/IPython/core/ultratb.py:1173, in VerboseTB.structured_traceback(self, etype, evalue, etb, tb_offset, number_of_lines_of_context)
   1164 def structured_traceback(
   1165     self,
   1166     etype: type,
   (...)
   1170     number_of_lines_of_context: int = 5,
   1171 ):
   1172     """Return a nice text document describing the traceback."""
-> 1173     formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,
   1174                                                            tb_offset)
   1176     colors = self.Colors  # just a shorthand + quicker name lookup
   1177     colorsnormal = colors.Normal  # used a lot

File venv/lib/python3.9/site-packages/IPython/core/ultratb.py:1063, in VerboseTB.format_exception_as_a_whole(self, etype, evalue, etb, number_of_lines_of_context, tb_offset)
   1060 assert isinstance(tb_offset, int)
   1061 head = self.prepare_header(str(etype), self.long_header)
   1062 records = (
-> 1063     self.get_records(etb, number_of_lines_of_context, tb_offset) if etb else []
   1064 )
   1066 frames = []
   1067 skipped = 0

File venv/lib/python3.9/site-packages/IPython/core/ultratb.py:1131, in VerboseTB.get_records(self, etb, number_of_lines_of_context, tb_offset)
   1129 while cf is not None:
   1130     try:
-> 1131         mod = inspect.getmodule(cf.tb_frame)
   1132         if mod is not None:
   1133             mod_name = mod.__name__

AttributeError: 'tuple' object has no attribute 'tb_frame'
The original exception:
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
Exception: outer exception

The above exception was the direct cause of the following exception:

FooExc                                    Traceback (most recent call last)
    [... skipping hidden 1 frame]

Cell In[7], line 1
----> 1 raise FooExc("outer exception") from Exception("outer exception")

FooExc: outer exception

During handling of the above exception, another exception occurred:

AttributeError                            Traceback (most recent call last)
File venv/lib/python3.9/site-packages/IPython/core/interactiveshell.py:2001, in InteractiveShell.set_custom_exc.<locals>.wrapped(self, etype, value, tb, tb_offset)
   2000 try:
-> 2001     stb = handler(self,etype,value,tb,tb_offset=tb_offset)
   2002     return validate_stb(stb)

Cell In[5], line 16, in my_handler(self, etype, value, tb, tb_offset)
     15 breakpoint()
---> 16 self.showtraceback(exc_tuple=(etype, value, tb), filename=None, tb_offset=tb_offset, exception_only=True)
     17 return traceback.format_tb(tb, tb_offset)

File venv/lib/python3.9/site-packages/IPython/core/interactiveshell.py:2123, in InteractiveShell.showtraceback(self, exc_tuple, filename, tb_offset, exception_only, running_compiled_code)
   2121     stb = ['An exception has occurred, use %tb to see '
   2122            'the full traceback.\n']
-> 2123     stb.extend(self.InteractiveTB.get_exception_only(etype,
   2124                                                      value))
   2125 else:

File venv/lib/python3.9/site-packages/IPython/core/ultratb.py:710, in ListTB.get_exception_only(self, etype, value)
    703 """Only print the exception type and message, without a traceback.
    704 
    705 Parameters
   (...)
    708 value : exception value
    709 """
--> 710 return ListTB.structured_traceback(self, etype, value)

File venv/lib/python3.9/site-packages/IPython/core/ultratb.py:568, in ListTB.structured_traceback(self, etype, evalue, etb, tb_offset, context)
    566     chained_exceptions_tb_offset = 0
    567     out_list = (
--> 568         self.structured_traceback(
    569             etype,
    570             evalue,
    571             (etb, chained_exc_ids),  # type: ignore
    572             chained_exceptions_tb_offset,
    573             context,
    574         )
    575         + chained_exception_message
    576         + out_list)
    578 return out_list

File venv/lib/python3.9/site-packages/IPython/core/ultratb.py:1435, in AutoFormattedTB.structured_traceback(self, etype, evalue, etb, tb_offset, number_of_lines_of_context)
   1434     self.tb = etb
-> 1435 return FormattedTB.structured_traceback(
   1436     self, etype, evalue, etb, tb_offset, number_of_lines_of_context
   1437 )

File venv/lib/python3.9/site-packages/IPython/core/ultratb.py:1326, in FormattedTB.structured_traceback(self, etype, value, tb, tb_offset, number_of_lines_of_context)
   1324 if mode in self.verbose_modes:
   1325     # Verbose modes need a full traceback
-> 1326     return VerboseTB.structured_traceback(
   1327         self, etype, value, tb, tb_offset, number_of_lines_of_context
   1328     )
   1329 elif mode == 'Minimal':

File venv/lib/python3.9/site-packages/IPython/core/ultratb.py:1173, in VerboseTB.structured_traceback(self, etype, evalue, etb, tb_offset, number_of_lines_of_context)
   1172 """Return a nice text document describing the traceback."""
-> 1173 formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,
   1174                                                        tb_offset)
   1176 colors = self.Colors  # just a shorthand + quicker name lookup

File venv/lib/python3.9/site-packages/IPython/core/ultratb.py:1063, in VerboseTB.format_exception_as_a_whole(self, etype, evalue, etb, number_of_lines_of_context, tb_offset)
   1061 head = self.prepare_header(str(etype), self.long_header)
   1062 records = (
-> 1063     self.get_records(etb, number_of_lines_of_context, tb_offset) if etb else []
   1064 )
   1066 frames = []

File venv/lib/python3.9/site-packages/IPython/core/ultratb.py:1131, in VerboseTB.get_records(self, etb, number_of_lines_of_context, tb_offset)
   1130 try:
-> 1131     mod = inspect.getmodule(cf.tb_frame)
   1132     if mod is not None:

AttributeError: 'tuple' object has no attribute 'tb_frame'

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
    [... skipping hidden 1 frame]

File venv/lib/python3.9/site-packages/IPython/core/interactiveshell.py:2011, in InteractiveShell.set_custom_exc.<locals>.wrapped(self, etype, value, tb, tb_offset)
   2009     print(self.InteractiveTB.stb2text(stb))
   2010     print("The original exception:")
-> 2011     stb = self.InteractiveTB.structured_traceback(
   2012                             (etype,value,tb), tb_offset=tb_offset
   2013     )
   2014 return stb

TypeError: structured_traceback() missing 1 required positional argument: 'evalue'
```
  
</details>

### Side notes
 - I could only get it in a notebook; I initially tried to reproduced by putting the code in a `tmp.py` file and calling `ipython tmp.py` but for some reasons it wouldn't call the custom exception handler.
 - My intuition here is that it is linked to exception chaining. In the snippet if you only `raise FooExc("outer exception")` without `from Exception("outer exception")`, the code behave as expected i.e. logging the error.

**Comment by meereeum** [comment]
+1, I get this error in a notebook (python 3.10.9) and it originates with a `raise $Exception from e` statement (from external library code)

**Comment by smacke** [comment]
I haven't looked carefully enough at the original issue but for `TypeError: structured_traceback() missing 1 required positional argument: 'evalue'`, I think https://github.com/ipython/ipython/pull/14453 can help

**Comment by amirhessam88** [comment]
I might me late to the party; I am using `click` as part of my pipelines in databricks (Python 3.10 - DBR - 14.3LTS that has click v8.0.4 and ipython v8.14.0 installed)

here is snippet:

```python
import click
@click.command()
@click.option(
    "--a",
    default=100,
    type=int,
    help="Parameter a",
)
@click.option(
    "--b",
    default=400,
    type=int,
    help="Parameter b",
)
def main(
    a: int,
    b: int,
) -> int:
    """Main entrypoint."""

    print(f"{a=} -- {b=}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
```

which raises `AttributeError: 'tuple' object has no attribute 'tb_frame'` once the run is finished.

I did also try the pattern 
```python
if __name__ == "__main__":
    try:
        main()
    except SystemExit as e:
        if e.code != 0:
            raise
```

still no luck ... is there any resolution on this issue ?

**Comment by smacke** [comment]
@amirhessam88 this is because the version of IPython on 14.3 is pinned to an older version of ipython that doesn't have the fix. Please raise to Databricks customer support and they can potentially work with eng to backport a patch to 14.3 (probably would end up being me on the ticket :). )

**Comment by amirhessam88** [comment]
Thanks @smacke; so, this is fixed as of `ipython v8.26.0` which is current version in PyPI ?

**Comment by smacke** [comment]
> Thanks @smacke; so, this is fixed as of ipython v8.26.0 which is current version in PyPI ?

I believe so (but could be wrong)
