### ISSUE TITLE
autoreload magic doesn't reload objects

### ISSUE THREAD

**Issue by stas00** [ipython/ipython#11588]
**update**: the problem appears to be with any object, unrelated to pickle. pickle was just exposing it in a forceful way. Skip to the latest diagnostic https://github.com/ipython/ipython/issues/11588#issuecomment-464949800

when autoreload reloads a python module, it appears to not be fully reloading the already instantiated objects, and pickle fails to pickle them with:

`Can't pickle <class 'mytestclass.Test'>: it's not the same object as mytestclass.Test`

Here is a notebook to reproduce, must be run in 3 parts (or 3 cells):

```
# cell1
%reload_ext autoreload
%autoreload 2

import pickle

file = "mytestclass.py"

text = """
class Test():
    def __init__(self):
        self.ok = 1
"""
with open("mytestclass.py","w") as f: f.write(text)

from mytestclass import *
test = Test()

# works
p = pickle.dumps(test)
```
```
# cell2
# touch forces autoreloader to reload the library file
!echo touch $file
!touch $file
```
```
# cell3
# now it fails
p = pickle.dumps(test)
```

The error is:

```
In [6]: p = pickle.dumps(test)
---------------------------------------------------------------------------
PicklingError                             Traceback (most recent call last)
<ipython-input-6-740c326b650e> in <module>()
----> 1 p = pickle.dumps(test)

PicklingError: Can't pickle <class 'mytestclass.Test'>: it's not the same object as mytestclass.Test

```

Please note that it should be run in 3 parts - if it's run in one go the reload effect won't be activated. Can be run in jupyter notebook or directly in ipython shell.

I traced why pickle fails and expanded on it in this issue https://github.com/fastai/fastai/issues/1493 - tldr; it compares memory addresses of the object's class and the class in `sys.modules` - if their memory addresses don't match it refuses to pickle.

I think there are other issues with the incomplete reload, (i.e. object methods disappearing after reload), but I'm yet to make reproducible cases for those. I believe pickle is just exposing a deeper problem.

I tried the git master ipython and went all the way back to ipython-6.0.0 - the problem is the same.

And yes, I read the caveats section, that does say that reload isn't 100% perfect.

Thank you.

**Comment by Carreau** [comment]
Thanks, I think it would make sens to try to fix this behavior and have autoreload not break pickle. I'm unsure how easy it would be.

**Comment by stas00** [comment]
So it looks like autoreload doesn't quite update the existing objects to the reloaded classes, here is for example how one could hack it into working:

```
# this is how pickle gets the current class to compare it later with the class of the object to be pickled
import sys
def pickle_get_current_class(obj):
    name = obj.__class__.__name__
    module_name = getattr(obj, '__module__', None)
    obj2 = sys.modules[module_name]
    for subpath in name.split('.'): obj2 = getattr(obj2, subpath)
    return obj2
```

So if we change cell3 in the code to reproduce this problem to be:

```
# cell3
# not it works
test.__class__ = pickle_get_current_class(test)
p = pickle.dumps(test)
```

So, this is how auto-reload could fix this issue.

**Comment by stas00** [comment]
Actually, it's not just pickle, autoreload basically doesn't reload the class at all, see:

```
#cell1
%reload_ext autoreload
%autoreload 2

file = "mytestclass.py"

text = """
class Test(): 
    def print(self): print("Old")
"""
with open("mytestclass.py","w") as f: f.write(text)

from mytestclass import *
test = Test()

# works
#p = pickle.dumps(test)
test.print()
```

```
#cell2
text = """
class Test(): 
    def print(self): print("New")
"""
with open("mytestclass.py","w") as f: f.write(text)
```
```
#cell3
test.print()
```

Both times it prints "Old". It should print "New" the second time.

**Comment by Carreau** [comment]
Yes, I do not believe autoreload update the current class of existing objects. I'm sure it is possible in Python, but I don't think we even try to do it. We could look up the MRO and modify it, but that might mean messing around with Ctypes.

**Comment by stas00** [comment]
Curiously, the [documentation (caveats)](https://ipython.org/ipython-doc/3/config/extensions/autoreload.html) says it tries to do so:

> %autoreload tries to work around common pitfalls by replacing function code objects and parts of classes previously in the module with new versions. This makes the following things to work:
> 
>     Functions and classes imported via ‘from xxx import foo’ are upgraded to new versions when ‘xxx’ is reloaded.
>     Methods and properties of classes are upgraded on reload, so that calling ‘c.foo()’ on an object ‘c’ created before the reload causes the new code for ‘foo’ to be executed.

Perhaps it used to do so and then this functionality was lost? Clearly with it failing on a such a basic test that I used in the demo, these docs are clearly wrong right now.

**Comment by Carreau** [comment]
Hum, so now I'm unsure. I rarely use it. But if it was doing it then: 
1) there should be a test for it
2) it's likely easier than I though to fix it :-)

**Comment by daharn** [comment]
I have looked into this a little. From what I see, only classes and functions within a reloaded module are updated, but instances of these classes are not touched. 

Updating these would be relatively straight forward setting
`instance.__class__ = new_class`
with `new_class` being the updated class reference.

Finding these instances is more complicated. The only way I can think of right now is passing `globals()` to the update function and iterate through all objects in the workspace (and recursively through all nested objects like lists, dicts etc.), checking whether
`isinstance(obj, old_class)`
and then doing the above update. 

Although I believe this would be the most logical behavior for `%autoreload`, I am not sure of the performance costs.

Any other ideas?

**Comment by stas00** [comment]
Unless you do get other ideas, @daharn - I'd say let's start with this method and if someone later comes up with a more efficient way, then it can be improved. But slower is better than broken, IMHO.

**Comment by reesehopkins** [comment]
FWIW, I tested @stas00's code works in IPython 7.2 and it works.

**Comment by edoson** [comment]
Hi,

Adding my few cents here - I see that autoreload works on the console (either instaciated by jupyter lab or from the terminal) but does not work from a jupyter notebook.

**Comment by liuzheng-arctic** [comment]
Hi,

I am having a similar issue. Autoreload works for me from a jupyter notebook but not in terminal. In terminal, I got the following message:
`AttributeError: module has no attribute '__name__'` 
Btw, I am using python 3.7.4 and ipython 7.8.0  .

**Comment by daharn** [comment]
Since your observations are exactly opposite, are you able to give reproducible examples of either error?

**Comment by jdanbrown** [comment]
Hmm, was this maybe fixed in 7.9.0 by https://github.com/ipython/ipython/pull/11876? I run into this error _all the time_ in my notebook workflows, and upgrading from ipython 7.7.0 to 7.11.1 appears to have fixed one instance where the error was occurring.

Does anyone have a robust set of repros that we can test?

**Comment by stas00** [comment]
So happy you noticed that change, @jdanbrown!

Indeed, both test cases that were failing: 
https://github.com/ipython/ipython/issues/11588#issuecomment-464949800
https://github.com/ipython/ipython/issues/11588#issue-405929887
no longer fail with ipython-7.9.0.

I'm not sure whether more tests are needed. I will start using the `%autoreload` feature again and see if I notice any more glitches.

**Comment by daharn** [comment]
At some point, I wasn't sure whether it also works for classes that were imported by `from <modulename> import <classname>`. Has anyone tested this already?

**Comment by stas00** [comment]
Have you looked at my test cases (links one comment up)? both of them do exactly that.

**Comment by daharn** [comment]
You are right. In that case, everything seems to work. Nested classes might be worth testing, too. I will look into my use cases again, too.

**Comment by daharn** [comment]
I found a remaining issue unrelated to Ipython: Breaking of the connection between instance and class leading to the initially described pickle problem can still occur under certain circumstances when using Spyder's user module reloader (UMR). 

Seems like I have come full circle, since I originally believed the problem to be UMR related:
https://github.com/spyder-ide/spyder/issues/8866

I will try to work up a MWE and continue the discussion in the Spyder forum.

**Comment by stas00** [comment]
so is it ok to close this issue then?

**Comment by liuzheng-arctic** [comment]
> Since your observations are exactly opposite, are you able to give reproducible examples of either error?

As is the case for another reply earlier. My issue is also fixed after an ipython upgrade.

**Comment by daharn** [comment]
> so is it ok to close this issue then?

Yes, go ahead. From the Ipython side, this seems to be solved.

**Comment by stas00** [comment]
Excellent! Glad this has been fixed! Thank you!
