### ISSUE TITLE
Spellchecker in Markdown and Heading cells

### ISSUE THREAD

**Issue by damianavila** [ipython/ipython#3216]
I would be great to have a spellchecker in text cells: headings and markdown cells...
Currently in Chrome and Firefox under Linux I have the "native" browser spellchecker not working. I think the problem is that Codemirror is filtering the cell content to not be spellcheked, but I would be great to have it functional... If we let the "native" spellchecker to do the job in text cells, we don't have to care about different languages and so on because it is a user configurable option at the browser level...
What do you think about that?

Damián.

**Comment by aloctavodia** [comment]
There is a keyboard shortcut to toggle on/off the spell checker? There is a way to alternate dictionaries without having to change the source code?

**Comment by dsblank** [comment]
Keyboard shortcut? No, not yet. We could also make the default "on". Change dictionaries? No, not yet. Pull Requests accepted! You can do that, and carry on this conversation here:

https://bitbucket.org/ipre/calico/issues?status=new&status=open

We hope to move these nbextensions out from this huge repo soon. Probably over to here:

https://github.com/calysto/

**Comment by rlabbe** [comment]
I want to note that I needed to put the following in custom.js to get this to work with IPython 3.0 (I'm on Windows 8, not sure that matters):

    require([ 
         'base/js/namespace', 
         'base/js/events' 
    ], function(IPython, events) { 
         events.on('app_initialized.NotebookApp', function(){ 
             IPython.load_extensions('calico-spell-check'); 
         }); 
     });

With the simpler 
    IPython.load_extensions('calico-spell-check'); 

mentioned above I got the javascript' undefined is not a function' error.

**Comment by NelisW** [comment]
First of all, thanks Doug and rlabbe!

[Marco Pinto](http://marcoagpinto.cidadevirtual.pt/proofingtoolgui.html) maintains a UK English hunspell-style list [here](https://github.com/marcoagpinto/aoo-mozilla-en-dict/tree/master/en_GB%20%28Marco%20Pinto%29%20-%202.23%20-%202015-04-01).  To implement the UK dictionary in an Anaconda IPython 3 installation  on Windows:

1.  Download the two files `en-GB.aff` and `en-GB.dic` into the (new) folder `C:\Anaconda\share\jupyter\nbextensions\typo\dictionaries\en_GB\`.  

2.  Rename the two files to use underscore instead of dash/hyphen (look at the en_US equivalent).  Change `en-GB.aff` to `en_GB.aff` and change `en-GB.dic` to `en_GB.dic`.

3. Edit the file `C:\Anaconda\share\jupyter\nbextensions\calico-spell-check.js` to replace `var lang = "en_US";` with `var lang = "en_GB";`.

It should be a simple matter to find the equivalent directories in Linux.

**Comment by NelisW** [comment]
BTW, it appears that you can edit (add new words?) dictionaries with Marco Pinto's tool available at http://marcoagpinto.cidadevirtual.pt/proofingtoolgui.html

**Comment by dsblank** [comment]
Thanks for all of these bits of information!

Also, one can add words to the calico-spell-check extension by making a
JSON object in a file named words.json and putting it next to
calico-spell-check.js.

BTW, we'll be splitting these Javascript extensions into their own project
so that it will be easier to make PRs.

-Doug

**Comment by NelisW** [comment]
Hi Doug,

I must thank you!  I am smiling ear-to-ear with my nice new spel checker in
IPython!

regards

n

**Comment by damianavila** [comment]
This issue is largely solved by @dsblank extension... so, I will close this issue, @dsblank please link here your project once splitted. Thanks.

**Comment by asmeurer** [comment]
So there's no hope of this every working natively?

**Comment by dsblank** [comment]
By natively, do you mean installed by default with the rest of ipython? I don't think that will probably happen because:

* it is a pretty large addon (700k expanded)
* ipython is breaking things up into smaller pieces as we speak
* it could still use some UI/development (changing languages, add words, picking suggested words, etc)

Of course, we would love to make it as easy to install as possible. There has been some discussion about whether pip should be used for something like this, or if Jupyter will have its own packaging system. I'm waiting to see what the recommendation is.

**Comment by asmeurer** [comment]
Yeah, or, better, support for the built in browser/OS spellchecker.

**Comment by takluyver** [comment]
It looks like @Carreau looked into that and thought that Codemirror broke the native browser spellchecker. Does anyone know otherwise?

**Comment by Carreau** [comment]
I think the issue is when CM is backed by a textarea instance, to OSX for example try to be "smart" and pop the completion window in a place innapropriate, which lock-up the UI. Also the wiggly underlines are in the textarea itself and not in CM  so won't be seen, and no API to access the Browser spellcheck....

**Comment by takluyver** [comment]
Long term solution: maybe we should ask browser makers for APIs to access spellchecking features.

**Comment by amueller** [comment]
Is the calico extension still working? It uses the deprecated nbextension and I couldn't make it work on ipython4.0:
```
%install_ext https://bitbucket.org/ipre/calico/downloads/calico-spell-check-1.0.zip
```
> Installed calico-spell-check-1.0.zip. To use it, type:
  %load_ext calico-spell-check-1.0
```
```
%load_ext calico-spell-check-1.0
```
> ImportError: No module named calico-spell-check-1.0

```
%load_ext calico-spell-check
```
> ImportError: No module named calico-spell-check

I also tried
```
%%javascript
require(['base/js/utils'],
function(utils) {
   utils.load_extensions('calico-spell-check', 'calico-document-tools', 'calico-cell-tools');
});
```
but that has no effect.

**Comment by amueller** [comment]
Ah, I guess ``%install_ext`` installs IPython extensions, not notebook extensions. Whoops. Still doing ``ipython install-nbextension https://bitbucket.org/ipre/calico/downloads/calico-spell-check-1.0.zip``also didn't help :-/

**Comment by rlabbe** [comment]
Is your notebook trusted? It won't show up if the notebook is not trusted.

**Comment by aloctavodia** [comment]
@amueller On Linux I did
```sudo jupyter nbextension install https://bitbucket.org/ipre/calico/downloads/calico-spell-check-1.0.zip```
followed by 
``` jupyter nbextension enable calico-spell-check```

BTW, I added an Spanish dictionary (to have both English and Spanish spellcheckers) but words with accents are marked as erroneous (this did not happen in previous Ipython and or callico versions).  Any idea?

**Comment by dsblank** [comment]
@aloctavodia Would you be willing to add or point to the spanish dictionary, and make an issue regarding the accented characters here:

https://github.com/Calysto/notebook-extensions/

**Comment by aloctavodia** [comment]
@dsblank Done it!
PS: sorry for posting the problem in the wrong place.

**Comment by dsblank** [comment]
Thanks! I'll take a look and try to replicate.

**Comment by AamirAbro** [comment]
Load wine data from file.

Data is loaded using *Pandas* as data frame; Read more about pandas here https://pandas.pydata.org/pandas-docs/stable/

Also by checking out **head** we can take a look at the data which gives us the overview of it.
