### ISSUE TITLE
The ipython 8.18.1 terminal failed

### ISSUE THREAD

**Issue by luoyebai** [ipython/ipython#14260]
Hi!
My English is not very good, so the following is all translated.
After I updated ipython to 8.18.1, I ran the ipython command in the terminal and got the following error
```shell
Python 3.11.6 (main, Nov 14 2023, 09:36:21) [GCC 13.2.1 20230801]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.18.1 -- An enhanced Interactive Python. Type '?' for help.

Traceback (most recent call last):
  File "/usr/bin/ipython", line 8, in <module>
    sys.exit(start_ipython())
             ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/IPython/__init__.py", line 129, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/traitlets/config/application.py", line 1077, in launch_instance
    app.start()
  File "/usr/lib/python3.11/site-packages/IPython/terminal/ipapp.py", line 317, in start
    self.shell.mainloop()
  File "/usr/lib/python3.11/site-packages/IPython/terminal/interactiveshell.py", line 887, in mainloop
    self.interact()
  File "/usr/lib/python3.11/site-packages/IPython/terminal/interactiveshell.py", line 872, in interact
    code = self.prompt_for_code()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/IPython/terminal/interactiveshell.py", line 813, in prompt_for_code
    text = self.pt_app.prompt(
           ^^^^^^^^^^^^^^^^^^^
TypeError: PromptSession.prompt() got an unexpected keyword argument 'inputhook'

If you suspect this is an IPython 8.18.1 bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True

```
I've noticed that my question is similar to the one below
[#14255](https://github.com/ipython/ipython/issues/14255)
But my python-prompt_toolkita version is 3.0.41-1
I did this by downgrading ipython to 8.17.2-1 and analyzing the difference between the two versions of the error file
/usr/lib/python3.11/site-packages/IPython/terminal/interactiveshell.py 
I found the /usr/lib/python3.11/site-packages/IPython/terminal/interactiveshell .py file different between the two versions

![image](https://github.com/ipython/ipython/assets/90087618/c9d786ed-2d82-4d50-9493-79059bda699a)

I modified line 634 of the file from 
```python
        self._use_asyncio_inputhook = False
```
to 
```python
        self._use_asyncio_inputhook = True
```
ipython will run normally in the terminal

**I don't know if there are some hidden dangers in doing this, if there is, hope to let me know, thank you for your patience and watching**

**Comment by luoyebai** [comment]
I found that the prompt_toolkita of version 3.0.39 exists under the
```
 ~/.local/lib/python3.11/site-packages 
```
This leads to the possibility of ipython
Incorrectly versioned dependencies are used, which is not an issue with ipython
Just need to remove the wrong dependencies
```
rm -r  ~/.local/lib/python3.11/site-packages/prompt_toolkit*
```

**Comment by toedtli** [comment]
I ran

    pip uninstall prompt_toolkit
    pip install prompt_toolkit

after which ipython started just fine.

**Comment by huxaiphaer** [comment]
> I ran
> 
> ```
> pip uninstall prompt_toolkit
> pip install prompt_toolkit
> ```
> 
> after which ipython started just fine.

This worked, thanks a bunch

**Comment by luccachiang** [comment]
`pip install -U ipython`
